logging:
  file:
    name: logs/msbatch.log
  pattern:
    file: '%d %-5level [%thread] %logger{0}: %msg%n'

spring:
  application:
    name: SflBillingMsBatch
  profiles:
    # The commented value for `active` can be replaced with valid Spring profiles to load.
    # Otherwise, it will be filled in by gradle when building the JAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    active: #spring.profiles.active#
    group:
      dev:
        - dev
        - api-docs
        - no-liquibase
        # Uncomment to activate TLS for the dev profile
        #- tls
  jmx:
    enabled: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    properties:
      hibernate.enable_lazy_load_no_trans: true
      hibernate.jdbc.time_zone: GMT-4
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      # modify batch size as necessary
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  messages:
    basename: i18n/messages
  main:
    allow-bean-definition-overriding: true
  task:
    execution:
      thread-name-prefix: ${spring.application.name}-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: ${spring.application.name}-scheduling-
      pool:
        size: 2
  thymeleaf:
    mode: HTML
  output:
    ansi:
      console-available: true
  cache:
    couchbase:
      expiration:

server:
  servlet:
    session:
      cookie:
        http-only: true

# Properties to be exposed on the /info management endpoint
info:
  # Comma separated list of profiles that will trigger the ribbon to show
  display-ribbon-on-profiles: 'dev'

coreprop:
#  api-docs:
#    default-include-pattern: ${server.servlet.context-path:}/api/.*
#    management-include-pattern: ${server.servlet.context-path:}/management/.*
#    title: Sfl Billing MsBatch API
#    description: BaseSfl API documentation
#    version: 0.0.1
#    terms-of-service-url:
#    contact-name:
#    contact-url:
#    contact-email:
#    license: unlicensed
#    license-url:
  security:
    content-security-policy: "default-src 'self'; frame-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://storage.googleapis.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:"

# application:
security:
  password : "sflb1ll1ing-ms4c0unt"
invoice:
  path-temp-folder: "/Users/xeio/tmp/invoice/"
  number-massive: 2000
  number-pack: 500
batch-validate:
  cron: "0 * * ? * *"
expiration:
  cron: "0 8,16 * ? * *"
  days : 30
notification:
  endpoint : "https://test.luminia.com.bo/notification-api-web/v1/send-email"
offline:
  cron: "*/30 * * * * ?"
  apiKey: "TokenApi eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJTSU5URVNJMjAyMCIsImNvZGlnb1Npc3RlbWEiOiI2RDI0MTI1OENBODI0OUE2NkZFQjhFRiIsIm5pdCI6Ikg0c0lBQUFBQUFBQUFETTBNTEl3TXpjMU1ESUJBSFl6bHZnS0FBQUEiLCJpZCI6MTA3NzE5MCwiZXhwIjoxNjcyNDQ0ODAwLCJpYXQiOjE2NDA5NjEzOTQsIm5pdERlbGVnYWRvIjoxMDI4Njc1MDI0LCJzdWJzaXN0ZW1hIjoiU0ZFIn0.bKwMU_WTie8psBT_Rm_lWyxaB5kvu03zDnbMv30tIdIIODvCa2fFcWdC9KL2urdefAs9kzV2rMgQquScEkkGrA"
  try-number: 3
siat:
  soap-service: "https://pilotosiatservicios.impuestos.gob.bo/v2/"
  soap-timeout-connect: 500
  soap-timeout-request: 15000
batch-revalidate-invoices:
  cron: "*/30 * * * * ?"
  quantity: 30
  url-qr: "https://pilotosiat.impuestos.gob.bo/consulta/QR?nit=%s&cuf=%s&numero=%s&t=0"
  seconds-from-emitted: 60
