
package bo.gob.impuestos.sfe.creditdebitnoteinvoice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioFacturacion", targetNamespace = "https://siat.impuestos.gob.bo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioFacturacion {


    /**
     * 
     * @param solicitudServicioAnulacionDocumentoAjuste
     * @return
     *     returns bo.gob.impuestos.sfe.creditdebitnoteinvoice.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "anulacionDocumentoAjuste", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.creditdebitnoteinvoice.AnulacionDocumentoAjuste")
    @ResponseWrapper(localName = "anulacionDocumentoAjusteResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.creditdebitnoteinvoice.AnulacionDocumentoAjusteResponse")
    public RespuestaRecepcion anulacionDocumentoAjuste(
        @WebParam(name = "SolicitudServicioAnulacionDocumentoAjuste", targetNamespace = "")
        SolicitudAnulacion solicitudServicioAnulacionDocumentoAjuste);

    /**
     * 
     * @return
     *     returns bo.gob.impuestos.sfe.creditdebitnoteinvoice.RespuestaComunicacion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verificarComunicacion", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.creditdebitnoteinvoice.VerificarComunicacion")
    @ResponseWrapper(localName = "verificarComunicacionResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.creditdebitnoteinvoice.VerificarComunicacionResponse")
    public RespuestaComunicacion verificarComunicacion();

    /**
     * 
     * @param solicitudServicioRecepcionDocumentoAjuste
     * @return
     *     returns bo.gob.impuestos.sfe.creditdebitnoteinvoice.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "recepcionDocumentoAjuste", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.creditdebitnoteinvoice.RecepcionDocumentoAjuste")
    @ResponseWrapper(localName = "recepcionDocumentoAjusteResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.creditdebitnoteinvoice.RecepcionDocumentoAjusteResponse")
    public RespuestaRecepcion recepcionDocumentoAjuste(
        @WebParam(name = "SolicitudServicioRecepcionDocumentoAjuste", targetNamespace = "")
        SolicitudRecepcionFactura solicitudServicioRecepcionDocumentoAjuste);

    /**
     * 
     * @param solicitudServicioVerificacionEstadoDocumentoAjuste
     * @return
     *     returns bo.gob.impuestos.sfe.creditdebitnoteinvoice.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "verificacionEstadoDocumentoAjuste", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.creditdebitnoteinvoice.VerificacionEstadoDocumentoAjuste")
    @ResponseWrapper(localName = "verificacionEstadoDocumentoAjusteResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.creditdebitnoteinvoice.VerificacionEstadoDocumentoAjusteResponse")
    public RespuestaRecepcion verificacionEstadoDocumentoAjuste(
        @WebParam(name = "SolicitudServicioVerificacionEstadoDocumentoAjuste", targetNamespace = "")
        SolicitudVerificacionEstado solicitudServicioVerificacionEstadoDocumentoAjuste);

}
