
package bo.gob.impuestos.sfe.financialinvoice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioFacturacion", targetNamespace = "https://siat.impuestos.gob.bo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioFacturacion {


    /**
     * 
     * @param solicitudServicioRecepcionPaquete
     * @return
     *     returns bo.gob.impuestos.sfe.financialinvoice.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "recepcionPaqueteFactura", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.financialinvoice.RecepcionPaqueteFactura")
    @ResponseWrapper(localName = "recepcionPaqueteFacturaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.financialinvoice.RecepcionPaqueteFacturaResponse")
    public RespuestaRecepcion recepcionPaqueteFactura(
        @WebParam(name = "SolicitudServicioRecepcionPaquete", targetNamespace = "")
        SolicitudRecepcionPaquete solicitudServicioRecepcionPaquete);

    /**
     * 
     * @return
     *     returns bo.gob.impuestos.sfe.financialinvoice.RespuestaComunicacion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verificarComunicacion", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.financialinvoice.VerificarComunicacion")
    @ResponseWrapper(localName = "verificarComunicacionResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.financialinvoice.VerificarComunicacionResponse")
    public RespuestaComunicacion verificarComunicacion();

    /**
     * 
     * @param solicitudServicioRecepcionFactura
     * @return
     *     returns bo.gob.impuestos.sfe.financialinvoice.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "recepcionFactura", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.financialinvoice.RecepcionFactura")
    @ResponseWrapper(localName = "recepcionFacturaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.financialinvoice.RecepcionFacturaResponse")
    public RespuestaRecepcion recepcionFactura(
        @WebParam(name = "SolicitudServicioRecepcionFactura", targetNamespace = "")
        SolicitudRecepcionFactura solicitudServicioRecepcionFactura);

    /**
     * 
     * @param solicitudServicioValidacionRecepcionMasiva
     * @return
     *     returns bo.gob.impuestos.sfe.financialinvoice.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "validacionRecepcionMasivaFactura", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.financialinvoice.ValidacionRecepcionMasivaFactura")
    @ResponseWrapper(localName = "validacionRecepcionMasivaFacturaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.financialinvoice.ValidacionRecepcionMasivaFacturaResponse")
    public RespuestaRecepcion validacionRecepcionMasivaFactura(
        @WebParam(name = "SolicitudServicioValidacionRecepcionMasiva", targetNamespace = "")
        SolicitudValidacionRecepcion solicitudServicioValidacionRecepcionMasiva);

    /**
     * 
     * @param solicitudServicioRecepcionMasiva
     * @return
     *     returns bo.gob.impuestos.sfe.financialinvoice.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "recepcionMasivaFactura", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.financialinvoice.RecepcionMasivaFactura")
    @ResponseWrapper(localName = "recepcionMasivaFacturaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.financialinvoice.RecepcionMasivaFacturaResponse")
    public RespuestaRecepcion recepcionMasivaFactura(
        @WebParam(name = "SolicitudServicioRecepcionMasiva", targetNamespace = "")
        SolicitudRecepcionMasiva solicitudServicioRecepcionMasiva);

    /**
     * 
     * @param solicitudServicioVerificacionEstadoFactura
     * @return
     *     returns bo.gob.impuestos.sfe.financialinvoice.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "verificacionEstadoFactura", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.financialinvoice.VerificacionEstadoFactura")
    @ResponseWrapper(localName = "verificacionEstadoFacturaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.financialinvoice.VerificacionEstadoFacturaResponse")
    public RespuestaRecepcion verificacionEstadoFactura(
        @WebParam(name = "SolicitudServicioVerificacionEstadoFactura", targetNamespace = "")
        SolicitudVerificacionEstado solicitudServicioVerificacionEstadoFactura);

    /**
     * 
     * @param solicitudServicioValidacionRecepcionPaquete
     * @return
     *     returns bo.gob.impuestos.sfe.financialinvoice.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "validacionRecepcionPaqueteFactura", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.financialinvoice.ValidacionRecepcionPaqueteFactura")
    @ResponseWrapper(localName = "validacionRecepcionPaqueteFacturaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.financialinvoice.ValidacionRecepcionPaqueteFacturaResponse")
    public RespuestaRecepcion validacionRecepcionPaqueteFactura(
        @WebParam(name = "SolicitudServicioValidacionRecepcionPaquete", targetNamespace = "")
        SolicitudValidacionRecepcion solicitudServicioValidacionRecepcionPaquete);

    /**
     * 
     * @param solicitudServicioAnulacionFactura
     * @return
     *     returns bo.gob.impuestos.sfe.financialinvoice.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "anulacionFactura", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.financialinvoice.AnulacionFactura")
    @ResponseWrapper(localName = "anulacionFacturaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.financialinvoice.AnulacionFacturaResponse")
    public RespuestaRecepcion anulacionFactura(
        @WebParam(name = "SolicitudServicioAnulacionFactura", targetNamespace = "")
        SolicitudAnulacion solicitudServicioAnulacionFactura);

}
