
package bo.gob.impuestos.sfe.code;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicioFacturacionCodigos", targetNamespace = "https://siat.impuestos.gob.bo/FacturacionCodigos", wsdlLocation = "https://pilotosiatservicios.impuestos.gob.bo/v2/FacturacionCodigos?wsdl")
public class ServicioFacturacionCodigos_Service
    extends Service
{

    private final static URL SERVICIOFACTURACIONCODIGOS_WSDL_LOCATION;
    private final static WebServiceException SERVICIOFACTURACIONCODIGOS_EXCEPTION;
    private final static QName SERVICIOFACTURACIONCODIGOS_QNAME = new QName("https://siat.impuestos.gob.bo/FacturacionCodigos", "ServicioFacturacionCodigos");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://pilotosiatservicios.impuestos.gob.bo/v2/FacturacionCodigos?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOFACTURACIONCODIGOS_WSDL_LOCATION = url;
        SERVICIOFACTURACIONCODIGOS_EXCEPTION = e;
    }

    public ServicioFacturacionCodigos_Service() {
        super(__getWsdlLocation(), SERVICIOFACTURACIONCODIGOS_QNAME);
    }

    public ServicioFacturacionCodigos_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOFACTURACIONCODIGOS_QNAME, features);
    }

    public ServicioFacturacionCodigos_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOFACTURACIONCODIGOS_QNAME);
    }

    public ServicioFacturacionCodigos_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOFACTURACIONCODIGOS_QNAME, features);
    }

    public ServicioFacturacionCodigos_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioFacturacionCodigos_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicioFacturacionCodigos
     */
    @WebEndpoint(name = "ServicioFacturacionCodigosPort")
    public ServicioFacturacionCodigos getServicioFacturacionCodigosPort() {
        return super.getPort(new QName("https://siat.impuestos.gob.bo/FacturacionCodigos", "ServicioFacturacionCodigosPort"), ServicioFacturacionCodigos.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioFacturacionCodigos
     */
    @WebEndpoint(name = "ServicioFacturacionCodigosPort")
    public ServicioFacturacionCodigos getServicioFacturacionCodigosPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://siat.impuestos.gob.bo/FacturacionCodigos", "ServicioFacturacionCodigosPort"), ServicioFacturacionCodigos.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOFACTURACIONCODIGOS_EXCEPTION!= null) {
            throw SERVICIOFACTURACIONCODIGOS_EXCEPTION;
        }
        return SERVICIOFACTURACIONCODIGOS_WSDL_LOCATION;
    }

}
