
package bo.gob.impuestos.sfe.code;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioFacturacionCodigos", targetNamespace = "https://siat.impuestos.gob.bo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioFacturacionCodigos {


    /**
     * 
     * @param solicitudVerificarNit
     * @return
     *     returns bo.gob.impuestos.sfe.code.RespuestaVerificarNit
     */
    @WebMethod
    @WebResult(name = "RespuestaVerificarNit", targetNamespace = "")
    @RequestWrapper(localName = "verificarNit", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.code.VerificarNit")
    @ResponseWrapper(localName = "verificarNitResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.code.VerificarNitResponse")
    public RespuestaVerificarNit verificarNit(
        @WebParam(name = "SolicitudVerificarNit", targetNamespace = "")
        SolicitudVerificarNit solicitudVerificarNit);

    /**
     * 
     * @return
     *     returns bo.gob.impuestos.sfe.code.RespuestaComunicacion
     */
    @WebMethod
    @WebResult(name = "RespuestaComunicacion", targetNamespace = "")
    @RequestWrapper(localName = "verificarComunicacion", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.code.VerificarComunicacion")
    @ResponseWrapper(localName = "verificarComunicacionResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.code.VerificarComunicacionResponse")
    public RespuestaComunicacion verificarComunicacion();

    /**
     * 
     * @param solicitudCuisMasivoSistemas
     * @return
     *     returns bo.gob.impuestos.sfe.code.RespuestaCuisMasivo
     */
    @WebMethod
    @WebResult(name = "RespuestaCuisMasivo", targetNamespace = "")
    @RequestWrapper(localName = "cuisMasivo", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.code.CuisMasivo")
    @ResponseWrapper(localName = "cuisMasivoResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.code.CuisMasivoResponse")
    public RespuestaCuisMasivo cuisMasivo(
        @WebParam(name = "SolicitudCuisMasivoSistemas", targetNamespace = "")
        SolicitudCuisMasivoSistemas solicitudCuisMasivoSistemas);

    /**
     * 
     * @param solicitudCufd
     * @return
     *     returns bo.gob.impuestos.sfe.code.RespuestaCufd
     */
    @WebMethod
    @WebResult(name = "RespuestaCufd", targetNamespace = "")
    @RequestWrapper(localName = "cufd", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.code.Cufd")
    @ResponseWrapper(localName = "cufdResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.code.CufdResponse")
    public RespuestaCufd cufd(
        @WebParam(name = "SolicitudCufd", targetNamespace = "")
        SolicitudCufd solicitudCufd);

    /**
     * 
     * @param solicitudNotificaRevocado
     * @return
     *     returns bo.gob.impuestos.sfe.code.RespuestaNotificaRevocado
     */
    @WebMethod
    @WebResult(name = "RespuestaNotificaRevocado", targetNamespace = "")
    @RequestWrapper(localName = "notificaCertificadoRevocado", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.code.NotificaCertificadoRevocado")
    @ResponseWrapper(localName = "notificaCertificadoRevocadoResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.code.NotificaCertificadoRevocadoResponse")
    public RespuestaNotificaRevocado notificaCertificadoRevocado(
        @WebParam(name = "SolicitudNotificaRevocado", targetNamespace = "")
        SolicitudNotifcaRevocado solicitudNotificaRevocado);

    /**
     * 
     * @param solicitudCuis
     * @return
     *     returns bo.gob.impuestos.sfe.code.RespuestaCuis
     */
    @WebMethod
    @WebResult(name = "RespuestaCuis", targetNamespace = "")
    @RequestWrapper(localName = "cuis", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.code.Cuis")
    @ResponseWrapper(localName = "cuisResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.code.CuisResponse")
    public RespuestaCuis cuis(
        @WebParam(name = "SolicitudCuis", targetNamespace = "")
        SolicitudCuis solicitudCuis);

    /**
     * 
     * @param solicitudCufdMasivo
     * @return
     *     returns bo.gob.impuestos.sfe.code.RespuestaCufdMasivo
     */
    @WebMethod
    @WebResult(name = "RespuestaCufdMasivo", targetNamespace = "")
    @RequestWrapper(localName = "cufdMasivo", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.code.CufdMasivo")
    @ResponseWrapper(localName = "cufdMasivoResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.code.CufdMasivoResponse")
    public RespuestaCufdMasivo cufdMasivo(
        @WebParam(name = "SolicitudCufdMasivo", targetNamespace = "")
        SolicitudCufdMasivo solicitudCufdMasivo);

}
