
package bo.gob.impuestos.sfe.operation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioFacturacionOperaciones", targetNamespace = "https://siat.impuestos.gob.bo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioFacturacionOperaciones {


    /**
     * 
     * @return
     *     returns bo.gob.impuestos.sfe.operation.RespuestaComunicacion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verificarComunicacion", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.operation.VerificarComunicacion")
    @ResponseWrapper(localName = "verificarComunicacionResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.operation.VerificarComunicacionResponse")
    public RespuestaComunicacion verificarComunicacion();

    /**
     * 
     * @param solicitudRegistroPuntoVenta
     * @return
     *     returns bo.gob.impuestos.sfe.operation.RespuestaRegistroPuntoVenta
     */
    @WebMethod
    @WebResult(name = "RespuestaRegistroPuntoVenta", targetNamespace = "")
    @RequestWrapper(localName = "registroPuntoVenta", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.operation.RegistroPuntoVenta")
    @ResponseWrapper(localName = "registroPuntoVentaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.operation.RegistroPuntoVentaResponse")
    public RespuestaRegistroPuntoVenta registroPuntoVenta(
        @WebParam(name = "SolicitudRegistroPuntoVenta", targetNamespace = "")
        SolicitudRegistroPuntoVenta solicitudRegistroPuntoVenta);

    /**
     * 
     * @param solicitudPuntoVentaComisionista
     * @return
     *     returns bo.gob.impuestos.sfe.operation.RespuestaPuntoVentaComisionista
     */
    @WebMethod
    @WebResult(name = "RespuestaPuntoVentaComisionista", targetNamespace = "")
    @RequestWrapper(localName = "registroPuntoVentaComisionista", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.operation.RegistroPuntoVentaComisionista")
    @ResponseWrapper(localName = "registroPuntoVentaComisionistaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.operation.RegistroPuntoVentaComisionistaResponse")
    public RespuestaPuntoVentaComisionista registroPuntoVentaComisionista(
        @WebParam(name = "SolicitudPuntoVentaComisionista", targetNamespace = "")
        SolicitudPuntoVentaComisionista solicitudPuntoVentaComisionista);

    /**
     * 
     * @param solicitudOperaciones
     * @return
     *     returns bo.gob.impuestos.sfe.operation.RespuestaCierreSistemas
     */
    @WebMethod
    @WebResult(name = "RespuestaCierreSistemas", targetNamespace = "")
    @RequestWrapper(localName = "cierreOperacionesSistema", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.operation.CierreOperacionesSistema")
    @ResponseWrapper(localName = "cierreOperacionesSistemaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.operation.CierreOperacionesSistemaResponse")
    public RespuestaCierreSistemas cierreOperacionesSistema(
        @WebParam(name = "SolicitudOperaciones", targetNamespace = "")
        SolicitudOperaciones solicitudOperaciones);

    /**
     * 
     * @param solicitudConsultaEvento
     * @return
     *     returns bo.gob.impuestos.sfe.operation.RespuestaListaEventos
     */
    @WebMethod
    @WebResult(name = "RespuestaListaEventos", targetNamespace = "")
    @RequestWrapper(localName = "consultaEventoSignificativo", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.operation.ConsultaEventoSignificativo")
    @ResponseWrapper(localName = "consultaEventoSignificativoResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.operation.ConsultaEventoSignificativoResponse")
    public RespuestaListaEventos consultaEventoSignificativo(
        @WebParam(name = "SolicitudConsultaEvento", targetNamespace = "")
        SolicitudConsultaEvento solicitudConsultaEvento);

    /**
     * 
     * @param solicitudConsultaPuntoVenta
     * @return
     *     returns bo.gob.impuestos.sfe.operation.RespuestaConsultaPuntoVenta
     */
    @WebMethod
    @WebResult(name = "RespuestaConsultaPuntoVenta", targetNamespace = "")
    @RequestWrapper(localName = "consultaPuntoVenta", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.operation.ConsultaPuntoVenta")
    @ResponseWrapper(localName = "consultaPuntoVentaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.operation.ConsultaPuntoVentaResponse")
    public RespuestaConsultaPuntoVenta consultaPuntoVenta(
        @WebParam(name = "SolicitudConsultaPuntoVenta", targetNamespace = "")
        SolicitudConsultaPuntoVenta solicitudConsultaPuntoVenta);

    /**
     * 
     * @param solicitudEventoSignificativo
     * @return
     *     returns bo.gob.impuestos.sfe.operation.RespuestaListaEventos
     */
    @WebMethod
    @WebResult(name = "RespuestaListaEventos", targetNamespace = "")
    @RequestWrapper(localName = "registroEventoSignificativo", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.operation.RegistroEventoSignificativo")
    @ResponseWrapper(localName = "registroEventoSignificativoResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.operation.RegistroEventoSignificativoResponse")
    public RespuestaListaEventos registroEventoSignificativo(
        @WebParam(name = "SolicitudEventoSignificativo", targetNamespace = "")
        SolicitudEventoSignificativo solicitudEventoSignificativo);

    /**
     * 
     * @param solicitudCierrePuntoVenta
     * @return
     *     returns bo.gob.impuestos.sfe.operation.RespuestaCierrePuntoVenta
     */
    @WebMethod
    @WebResult(name = "RespuestaCierrePuntoVenta", targetNamespace = "")
    @RequestWrapper(localName = "cierrePuntoVenta", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.operation.CierrePuntoVenta")
    @ResponseWrapper(localName = "cierrePuntoVentaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.operation.CierrePuntoVentaResponse")
    public RespuestaCierrePuntoVenta cierrePuntoVenta(
        @WebParam(name = "SolicitudCierrePuntoVenta", targetNamespace = "")
        SolicitudCierrePuntoVenta solicitudCierrePuntoVenta);

}
