
package bo.gob.impuestos.sfe.operation;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicioFacturacionOperaciones", targetNamespace = "https://siat.impuestos.gob.bo/FacturacionOperaciones", wsdlLocation = "https://pilotosiatservicios.impuestos.gob.bo/v2/FacturacionOperaciones?wsdl")
public class ServicioFacturacionOperaciones_Service
    extends Service
{

    private final static URL SERVICIOFACTURACIONOPERACIONES_WSDL_LOCATION;
    private final static WebServiceException SERVICIOFACTURACIONOPERACIONES_EXCEPTION;
    private final static QName SERVICIOFACTURACIONOPERACIONES_QNAME = new QName("https://siat.impuestos.gob.bo/FacturacionOperaciones", "ServicioFacturacionOperaciones");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://pilotosiatservicios.impuestos.gob.bo/v2/FacturacionOperaciones?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOFACTURACIONOPERACIONES_WSDL_LOCATION = url;
        SERVICIOFACTURACIONOPERACIONES_EXCEPTION = e;
    }

    public ServicioFacturacionOperaciones_Service() {
        super(__getWsdlLocation(), SERVICIOFACTURACIONOPERACIONES_QNAME);
    }

    public ServicioFacturacionOperaciones_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOFACTURACIONOPERACIONES_QNAME, features);
    }

    public ServicioFacturacionOperaciones_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOFACTURACIONOPERACIONES_QNAME);
    }

    public ServicioFacturacionOperaciones_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOFACTURACIONOPERACIONES_QNAME, features);
    }

    public ServicioFacturacionOperaciones_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioFacturacionOperaciones_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicioFacturacionOperaciones
     */
    @WebEndpoint(name = "ServicioFacturacionOperacionesPort")
    public ServicioFacturacionOperaciones getServicioFacturacionOperacionesPort() {
        return super.getPort(new QName("https://siat.impuestos.gob.bo/FacturacionOperaciones", "ServicioFacturacionOperacionesPort"), ServicioFacturacionOperaciones.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioFacturacionOperaciones
     */
    @WebEndpoint(name = "ServicioFacturacionOperacionesPort")
    public ServicioFacturacionOperaciones getServicioFacturacionOperacionesPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://siat.impuestos.gob.bo/FacturacionOperaciones", "ServicioFacturacionOperacionesPort"), ServicioFacturacionOperaciones.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOFACTURACIONOPERACIONES_EXCEPTION!= null) {
            throw SERVICIOFACTURACIONOPERACIONES_EXCEPTION;
        }
        return SERVICIOFACTURACIONOPERACIONES_WSDL_LOCATION;
    }

}
