name: luminia-sfl

services:
  invoice:
    container_name: invoicems-sfl
    image: ghcr.io/luminia-bo/sflbilling-msinvoice:${MSINVOICE_IMAGE_VERSION:-latest}
    restart: unless-stopped
    mem_limit: ${MEM_LIMIT:-512mb}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${LOGS_DIR:-~/logs/sflbilling}/invoice/:/var/log/app/
    environment:
      _JAVA_OPTIONS: ${JAVA_OPTS:-}
      TZ: America/La_Paz
      SPRING_PROFILES_ACTIVE: prod,no-liquibase
      LOGGING_FILE_NAME: /var/log/app/invoicems.log
      LOGGING_LEVEL_BO_COM_LUMINIA_SFLBILLING_MSINVOICE: ${MSINVOICE_LEVEL_LOG:-debug}
      LOGGING_LOGBACK_ROLLINGPOLICY_MAX_FILE_SIZE: ${LOGGIN_MAX_FILE_SIZE:-500MB}
      LOGGING_LOGBACK_ROLLINGPOLICY_MAX_HISTORY: ${LOGGIN_MAX_HISTORY:-90}
      SPRING_DATASOURCE_URL: ${DATASOURCE_URL:-jdbc:postgresql://172.20.0.6:5432/sflbilling}
      SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USERNAME:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD:-postgres}
      COREPROP_SECURITY_AUTHENTICATION_JWT_BASE64_SECRET: ${JWT_BASE64_SECRET:-TJSLuDMphFgnGyl4SKUwERTHToKVcRioe2d/WP1iTTJU4B9oWgFyiDm/A/sYOCbc2J6KYcc/HrYK/k/NJg+rpQ==}
      # Cors
      COREPROP_CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-}
      COREPROP_CORS_ALLOWED_METHODS: ${CORS_ALLOWED_METHODS:-}
      COREPROP_CORS_ALLOWED_HEADERS: ${CORS_ALLOWED_HEADERS:-}
      COREPROP_CORS_EXPOSED_HEADERS: ${CORS_EXPOSED_HEADERS:-Authorization,Link,X-Total-Count}
      COREPROP_CORS_ALLOW_CREDENTIALS: ${CORS_ALLOW_CREDENTIALS:-true}
      COREPROP_CORS_MAX_AGE: ${CORS_MAX_AGE:-1800}
      # App env
      INVOICE_NUMBER_LIMIT_BATCH: 500
      INVOICE_PRINT_EMIT_CRON_DETAIL: ${INVOICE_PRINT_EMIT_CRON_DETAIL:-true}
      INVOICE_TIME_SEND_SIAT: 2000
      NOTIFICATION_ENDPOINT: http://172.20.0.12:8083/api/email/send
      NOTIFICATION_ENDPOINT_EMAIL: ${NOTIFICATION_ENDPOINT:-http://199.3.0.227:8080/api/email/send}
      CANCELLATION_TERM_DAYS: 9
      CANCELLATION_TERM_DAYS_COMERCIAL_EXPORTACION: 180
      SIAT_SOAP_SERVICE: ${SIAT_SOAP_URL:-https://pilotosiatservicios.impuestos.gob.bo}/v2/
      SIAT_SKIP_CHECK_EVENTS: ${SIAT_SKIP_CHECK:-true}
      SIAT_SOAP_ENABLE_HANDLER_INVOICE: ${SIAT_SOAP_ENABLE_HANDLER_INVOICE:-false}
      USE_SAVED_IDENTITY_DOCUMENT_TYPES: ${USE_SAVED_IDENTITY_DOCUMENT_TYPES:-true}