name: luminia-sfl

services:
  batch:
    container_name: batchms-sfl
    image: ghcr.io/luminia-bo/sflbilling-msbatch:${MSBATCH_IMAGE_VERSION:-latest}
    restart: unless-stopped
    mem_limit: ${MEM_LIMIT:-512mb}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${LOGS_DIR:-~/logs/sflbilling}/batch/:/var/log/app/
      - ~/sfl-resources/invoices/:/app/invoices/
    environment:
      _JAVA_OPTIONS: ${JAVA_OPTS:-}
      TZ: America/La_Paz
      SPRING_PROFILES_ACTIVE: prod,no-liquibase
      LOGGING_FILE_NAME: /var/log/app/batchms.log
      LOGGING_LEVEL_BO_COM_LUMINIA_SFLBILLING_MSBATCH: ${MSBATCH_LEVEL_LOG:-debug}
      LOGGING_LOGBACK_ROLLINGPOLICY_MAX_FILE_SIZE: ${LOGGIN_MAX_FILE_SIZE:-500MB}
      LOGGING_LOGBACK_ROLLINGPOLICY_MAX_HISTORY: ${LOGGIN_MAX_HISTORY:-90}
      SPRING_DATASOURCE_URL: ${DATASOURCE_URL:-jdbc:postgresql://172.20.0.6:5432/sflbilling}
      SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USERNAME:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD:-postgres}
      COREPROP_SECURITY_AUTHENTICATION_JWT_BASE64_SECRET: ${JWT_BASE64_SECRET:-TJSLuDMphFgnGyl4SKUwERTHToKVcRioe2d/WP1iTTJU4B9oWgFyiDm/A/sYOCbc2J6KYcc/HrYK/k/NJg+rpQ==}
      # Cors
      COREPROP_CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-}
      COREPROP_CORS_ALLOWED_METHODS: ${CORS_ALLOWED_METHODS:-}
      COREPROP_CORS_ALLOWED_HEADERS: ${CORS_ALLOWED_HEADERS:-}
      COREPROP_CORS_EXPOSED_HEADERS: ${CORS_EXPOSED_HEADERS:-Authorization,Link,X-Total-Count}
      COREPROP_CORS_ALLOW_CREDENTIALS: ${CORS_ALLOW_CREDENTIALS:-true}
      COREPROP_CORS_MAX_AGE: ${CORS_MAX_AGE:-1800}
      # App env
      INVOICE_PATH_TEMP_FOLDER: /app/invoices/
      INVOICE_NUMBER_MASSIVE: 2000
      INVOICE_NUMBER_PACK: 500
      BATCH_VALIDATE_CRON: '0 * * ? * *'
      EXPIRATION_CRON: '0 0 8 * * ?'
      EXPIRATION_DAYS: 30
      NOTIFICATION_ENDPOINT: ${NOTIFICATION_ENDPOINT:-http://199.3.0.227:8080/api/email/send}
      NOTIFICATION_ONLINE_OFFLINE_STAGE: ${NOTIFICATION_ONLINE_OFFLINE_STAGE:-produccion}
      NOTIFICATION_ONLINE_OFFLINE_EMAIL: ${NOTIFICATION_ONLINE_OFFLINE_EMAIL:-abelm@luminia.com.bo}
      ONLINE_PACK_CRON: ${BATCH_ONLINE_PACK_CRON:-*/40 * * * * ?}
      ONLINE_VALIDATE_CRON: ${BATCH_ONLINE_VALIDATE_CRON:-*/45 * * * * ?}
      OFFLINE_CRON: ${BATCH_OFFLINE_CRON:-*/30 * * * * ?}
      OFFLINE_API_KEY: ${BATCH_OFFLINE_API_KEY:-TokenApi eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJTSU5URVNJMjAyMCIsImNvZGlnb1Npc3RlbWEiOiI2RDI0MTI1OENBODI0OUE2NkZFQjhFRiIsIm5pdCI6Ikg0c0lBQUFBQUFBQUFETTBNTEl3TXpjMU1ESUJBSFl6bHZnS0FBQUEiLCJpZCI6MTA3NzE5MCwiZXhwIjoxNjcyNDQ0ODAwLCJpYXQiOjE2NDA5NjEzOTQsIm5pdERlbGVnYWRvIjoxMDI4Njc1MDI0LCJzdWJzaXN0ZW1hIjoiU0ZFIn0.bKwMU_WTie8psBT_Rm_lWyxaB5kvu03zDnbMv30tIdIIODvCa2fFcWdC9KL2urdefAs9kzV2rMgQquScEkkGrA}
      OFFLINE_TRY_NUMBER: ${BATCH_OFFLINE_TRY_NUMBER:-3}
      OFFLINE_TRY_TIME_CONNECTION: ${BATCH_OFFLINE_TRY_TIME_CONNECTION:-2000}
      SIAT_SOAP_SERVICE: ${SIAT_SOAP_URL:-https://pilotosiatservicios.impuestos.gob.bo}/v2/
      SIAT_SOAP_TIMEOUT_CONNECT: ${SIAT_SOAP_TIMEOUT_CONNECT:-500}
      SIAT_SOAP_TIMEOUT_REQUEST: ${SIAT_SOAP_TIMEOUT_REQUEST:-15000}
      CONNECTIVITY_CHECK_METHOD: ${CONNECTIVITY_CHECK_METHOD:-2}
      CONNECTIVITY_HOST: ${CONNECTIVITY_HOST:-pilotosiatservicios.impuestos.gob.bo}
      CONNECTIVITY_PORT: ${CONNECTIVITY_PORT:-443}
      CONNECTIVITY_TIMEOUT: ${CONNECTIVITY_TIMEOUT:-500}
      BATCH_REVALIDATE_INVOICES_QUANTITY: ${BATCH_REVALIDATE_INVOICES_QUANTITY:-30}
      BATCH_REVALIDATE_INVOICES_URL_QR: ${BATCH_REVALIDATE_INVOICES_URL_QR:-https://pilotosiat.impuestos.gob.bo/consulta/QR?nit=%s&cuf=%s&numero=%s&t=0}
      BATCH_REVALIDATE_INVOICES_CRON: ${BATCH_REVALIDATE_INVOICES_CRON:-*/30 * * * * ?}
      BATCH_REVALIDATE_INVOICES_SECONDS_FROM_EMITTED: ${BATCH_REVALIDATE_INVOICES_SECONDS_FROM_EMITTED:-60}
      BATCH_REVALIDATE_INVOICES_CRON_FAILED: ${BATCH_REVALIDATE_INVOICES_CRON:-*/30 * * * * ?}
      BATCH_REVALIDATE_INVOICES_QUANTITY_FAILED: ${BATCH_REVALIDATE_INVOICES_QUANTITY_FAILED:-10}
      SFL_INTEGRATION_URL_LOGIN: ${SFL_INTEGRATION_URL_LOGIN:-http://141.94.244.182:8000/account/api/authenticate}
      SFL_INTEGRATION_USER: ${SFL_INTEGRATION_USER:-admin}
      SFL_INTEGRATION_PASSWORD: ${SFL_INTEGRATION_PASSWORD:-admin}
      SFL_INTEGRATION_URL_REVERT_FORCE: ${SFL_INTEGRATION_URL_REVERT_FORCE:-http://199.3.0.179:8000/invoice/api/invoices/cancellationsforce}
      CHECK_TOKEN_CERTIFICATE_CRON: ${CHECK_TOKEN_CERTIFICATE_CRON:-0 0 6 * * ?}
      CHECK_TOKEN_CERTIFICATE_DAYS_TO_NOTIFY: ${CHECK_TOKEN_CERTIFICATE_DAYS_TO_NOTIFY:-30}