log_format sfl_json escape=json
'{'
'"timestamp":"$time_iso8601",'
'"client":"$remote_addr",'
'"upstream":"$upstream_addr",'
'"request":"$request",'
'"uri":"$uri",'
'"status":$status,'
'"rxBytes":$request_length,'
'"txBytes":$bytes_sent,'
'"apiName":"$api_name"'
'}';