upstream account_api {
    zone account_api 64k;
    server account1:8081;
    server account2:8081;
}
upstream invoice_api {
    zone invoice_api 64k;
    server invoice1:8082;
    server invoice2:8082;
}
upstream report_api {
    zone report_api 64k;
    server report1:8083;
    server report2:8083;
}
upstream batch_api {
    zone batch_api 64k;
    server batch1:8084;
    server batch2:8084;
}