# SFL billing
limit_req_zone $binary_remote_addr zone=account_api_zone:10m rate=300r/s;
limit_req_zone $binary_remote_addr zone=invoice_api_zone:10m rate=300r/s;
limit_req_zone $binary_remote_addr zone=report_api_zone:10m rate=300r/s;
limit_req_zone $binary_remote_addr zone=batch_api_zone:10m rate=300r/s;