server {
    listen 80;
    server_name _;

    set $api_name "-";
    access_log /var/log/nginx/sflapi.json sfl_json;

    location /account {
        set $api_name "AccountApi";
        rewrite ^/account(.*)$ $1 break;
        proxy_pass http://account_api;
    }
    location /invoice {
        set $api_name "InvoiceApi";
        rewrite ^/invoice(.*)$ $1 break;
        proxy_pass http://invoice_api;
    }
    location /report {
        set $api_name "ReportApi";
        rewrite ^/report(.*)$ $1 break;
        proxy_pass http://report_api;
    }
    location /batch {
        set $api_name "BatchApi";
        rewrite ^/batch(.*)$ $1 break;
        proxy_pass http://batch_api;
    }

    #proxy_intercept_errors on;
    include /etc/nginx/utils/api_json_errors.conf;
    default_type application/json;
}
