
package bo.gob.impuestos.sfe.synchronization;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioFacturacionSincronizacion", targetNamespace = "https://siat.impuestos.gob.bo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioFacturacionSincronizacion {


    /**
     * 
     * @param solicitudSincronizacion
     * @return
     *     returns bo.gob.impuestos.sfe.synchronization.RespuestaListaParametricas
     */
    @WebMethod
    @WebResult(name = "RespuestaListaParametricas", targetNamespace = "")
    @RequestWrapper(localName = "sincronizarParametricaMotivoAnulacion", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarParametricaMotivoAnulacion")
    @ResponseWrapper(localName = "sincronizarParametricaMotivoAnulacionResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarParametricaMotivoAnulacionResponse")
    public RespuestaListaParametricas sincronizarParametricaMotivoAnulacion(
        @WebParam(name = "SolicitudSincronizacion", targetNamespace = "")
        SolicitudSincronizacion solicitudSincronizacion);

    /**
     * 
     * @param solicitudSincronizacion
     * @return
     *     returns bo.gob.impuestos.sfe.synchronization.RespuestaListaActividades
     */
    @WebMethod
    @WebResult(name = "RespuestaListaActividades", targetNamespace = "")
    @RequestWrapper(localName = "sincronizarActividades", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarActividades")
    @ResponseWrapper(localName = "sincronizarActividadesResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarActividadesResponse")
    public RespuestaListaActividades sincronizarActividades(
        @WebParam(name = "SolicitudSincronizacion", targetNamespace = "")
        SolicitudSincronizacion solicitudSincronizacion);

    /**
     * 
     * @param solicitudSincronizacion
     * @return
     *     returns bo.gob.impuestos.sfe.synchronization.RespuestaFechaHora
     */
    @WebMethod
    @WebResult(name = "RespuestaFechaHora", targetNamespace = "")
    @RequestWrapper(localName = "sincronizarFechaHora", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarFechaHora")
    @ResponseWrapper(localName = "sincronizarFechaHoraResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarFechaHoraResponse")
    public RespuestaFechaHora sincronizarFechaHora(
        @WebParam(name = "SolicitudSincronizacion", targetNamespace = "")
        SolicitudSincronizacion solicitudSincronizacion);

    /**
     * 
     * @param solicitudSincronizacion
     * @return
     *     returns bo.gob.impuestos.sfe.synchronization.RespuestaListaParametricasLeyendas
     */
    @WebMethod
    @WebResult(name = "RespuestaListaParametricasLeyendas", targetNamespace = "")
    @RequestWrapper(localName = "sincronizarListaLeyendasFactura", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarListaLeyendasFactura")
    @ResponseWrapper(localName = "sincronizarListaLeyendasFacturaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarListaLeyendasFacturaResponse")
    public RespuestaListaParametricasLeyendas sincronizarListaLeyendasFactura(
        @WebParam(name = "SolicitudSincronizacion", targetNamespace = "")
        SolicitudSincronizacion solicitudSincronizacion);

    /**
     * 
     * @param solicitudSincronizacion
     * @return
     *     returns bo.gob.impuestos.sfe.synchronization.RespuestaListaParametricas
     */
    @WebMethod
    @WebResult(name = "RespuestaListaParametricas", targetNamespace = "")
    @RequestWrapper(localName = "sincronizarParametricaTipoHabitacion", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarParametricaTipoHabitacion")
    @ResponseWrapper(localName = "sincronizarParametricaTipoHabitacionResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarParametricaTipoHabitacionResponse")
    public RespuestaListaParametricas sincronizarParametricaTipoHabitacion(
        @WebParam(name = "SolicitudSincronizacion", targetNamespace = "")
        SolicitudSincronizacion solicitudSincronizacion);

    /**
     * 
     * @param solicitudSincronizacion
     * @return
     *     returns bo.gob.impuestos.sfe.synchronization.RespuestaListaActividadesDocumentoSector
     */
    @WebMethod
    @WebResult(name = "RespuestaListaActividadesDocumentoSector", targetNamespace = "")
    @RequestWrapper(localName = "sincronizarListaActividadesDocumentoSector", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarListaActividadesDocumentoSector")
    @ResponseWrapper(localName = "sincronizarListaActividadesDocumentoSectorResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarListaActividadesDocumentoSectorResponse")
    public RespuestaListaActividadesDocumentoSector sincronizarListaActividadesDocumentoSector(
        @WebParam(name = "SolicitudSincronizacion", targetNamespace = "")
        SolicitudSincronizacion solicitudSincronizacion);

    /**
     * 
     * @param solicitudSincronizacion
     * @return
     *     returns bo.gob.impuestos.sfe.synchronization.RespuestaListaParametricas
     */
    @WebMethod
    @WebResult(name = "RespuestaListaParametricas", targetNamespace = "")
    @RequestWrapper(localName = "sincronizarParametricaTipoDocumentoIdentidad", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarParametricaTipoDocumentoIdentidad")
    @ResponseWrapper(localName = "sincronizarParametricaTipoDocumentoIdentidadResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarParametricaTipoDocumentoIdentidadResponse")
    public RespuestaListaParametricas sincronizarParametricaTipoDocumentoIdentidad(
        @WebParam(name = "SolicitudSincronizacion", targetNamespace = "")
        SolicitudSincronizacion solicitudSincronizacion);

    /**
     * 
     * @param solicitudSincronizacion
     * @return
     *     returns bo.gob.impuestos.sfe.synchronization.RespuestaListaParametricas
     */
    @WebMethod
    @WebResult(name = "RespuestaListaParametricas", targetNamespace = "")
    @RequestWrapper(localName = "sincronizarParametricaUnidadMedida", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarParametricaUnidadMedida")
    @ResponseWrapper(localName = "sincronizarParametricaUnidadMedidaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarParametricaUnidadMedidaResponse")
    public RespuestaListaParametricas sincronizarParametricaUnidadMedida(
        @WebParam(name = "SolicitudSincronizacion", targetNamespace = "")
        SolicitudSincronizacion solicitudSincronizacion);

    /**
     * 
     * @param solicitudSincronizacion
     * @return
     *     returns bo.gob.impuestos.sfe.synchronization.RespuestaListaParametricas
     */
    @WebMethod
    @WebResult(name = "RespuestaListaParametricas", targetNamespace = "")
    @RequestWrapper(localName = "sincronizarParametricaTipoDocumentoSector", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarParametricaTipoDocumentoSector")
    @ResponseWrapper(localName = "sincronizarParametricaTipoDocumentoSectorResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarParametricaTipoDocumentoSectorResponse")
    public RespuestaListaParametricas sincronizarParametricaTipoDocumentoSector(
        @WebParam(name = "SolicitudSincronizacion", targetNamespace = "")
        SolicitudSincronizacion solicitudSincronizacion);

    /**
     * 
     * @param solicitudSincronizacion
     * @return
     *     returns bo.gob.impuestos.sfe.synchronization.RespuestaListaParametricas
     */
    @WebMethod
    @WebResult(name = "RespuestaListaParametricas", targetNamespace = "")
    @RequestWrapper(localName = "sincronizarParametricaTiposFactura", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarParametricaTiposFactura")
    @ResponseWrapper(localName = "sincronizarParametricaTiposFacturaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarParametricaTiposFacturaResponse")
    public RespuestaListaParametricas sincronizarParametricaTiposFactura(
        @WebParam(name = "SolicitudSincronizacion", targetNamespace = "")
        SolicitudSincronizacion solicitudSincronizacion);

    /**
     * 
     * @return
     *     returns bo.gob.impuestos.sfe.synchronization.RespuestaComunicacion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verificarComunicacion", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.VerificarComunicacion")
    @ResponseWrapper(localName = "verificarComunicacionResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.VerificarComunicacionResponse")
    public RespuestaComunicacion verificarComunicacion();

    /**
     * 
     * @param solicitudSincronizacion
     * @return
     *     returns bo.gob.impuestos.sfe.synchronization.RespuestaListaParametricas
     */
    @WebMethod
    @WebResult(name = "RespuestaListaParametricas", targetNamespace = "")
    @RequestWrapper(localName = "sincronizarListaMensajesServicios", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarListaMensajesServicios")
    @ResponseWrapper(localName = "sincronizarListaMensajesServiciosResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarListaMensajesServiciosResponse")
    public RespuestaListaParametricas sincronizarListaMensajesServicios(
        @WebParam(name = "SolicitudSincronizacion", targetNamespace = "")
        SolicitudSincronizacion solicitudSincronizacion);

    /**
     * 
     * @param solicitudSincronizacion
     * @return
     *     returns bo.gob.impuestos.sfe.synchronization.RespuestaListaParametricas
     */
    @WebMethod
    @WebResult(name = "RespuestaListaParametricas", targetNamespace = "")
    @RequestWrapper(localName = "sincronizarParametricaTipoMetodoPago", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarParametricaTipoMetodoPago")
    @ResponseWrapper(localName = "sincronizarParametricaTipoMetodoPagoResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarParametricaTipoMetodoPagoResponse")
    public RespuestaListaParametricas sincronizarParametricaTipoMetodoPago(
        @WebParam(name = "SolicitudSincronizacion", targetNamespace = "")
        SolicitudSincronizacion solicitudSincronizacion);

    /**
     * 
     * @param solicitudSincronizacion
     * @return
     *     returns bo.gob.impuestos.sfe.synchronization.RespuestaListaParametricas
     */
    @WebMethod
    @WebResult(name = "RespuestaListaParametricas", targetNamespace = "")
    @RequestWrapper(localName = "sincronizarParametricaEventosSignificativos", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarParametricaEventosSignificativos")
    @ResponseWrapper(localName = "sincronizarParametricaEventosSignificativosResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarParametricaEventosSignificativosResponse")
    public RespuestaListaParametricas sincronizarParametricaEventosSignificativos(
        @WebParam(name = "SolicitudSincronizacion", targetNamespace = "")
        SolicitudSincronizacion solicitudSincronizacion);

    /**
     * 
     * @param solicitudSincronizacion
     * @return
     *     returns bo.gob.impuestos.sfe.synchronization.RespuestaListaParametricas
     */
    @WebMethod
    @WebResult(name = "RespuestaListaParametricas", targetNamespace = "")
    @RequestWrapper(localName = "sincronizarParametricaTipoPuntoVenta", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarParametricaTipoPuntoVenta")
    @ResponseWrapper(localName = "sincronizarParametricaTipoPuntoVentaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarParametricaTipoPuntoVentaResponse")
    public RespuestaListaParametricas sincronizarParametricaTipoPuntoVenta(
        @WebParam(name = "SolicitudSincronizacion", targetNamespace = "")
        SolicitudSincronizacion solicitudSincronizacion);

    /**
     * 
     * @param solicitudSincronizacion
     * @return
     *     returns bo.gob.impuestos.sfe.synchronization.RespuestaListaProductos
     */
    @WebMethod
    @WebResult(name = "RespuestaListaProductos", targetNamespace = "")
    @RequestWrapper(localName = "sincronizarListaProductosServicios", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarListaProductosServicios")
    @ResponseWrapper(localName = "sincronizarListaProductosServiciosResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarListaProductosServiciosResponse")
    public RespuestaListaProductos sincronizarListaProductosServicios(
        @WebParam(name = "SolicitudSincronizacion", targetNamespace = "")
        SolicitudSincronizacion solicitudSincronizacion);

    /**
     * 
     * @param solicitudSincronizacion
     * @return
     *     returns bo.gob.impuestos.sfe.synchronization.RespuestaListaParametricas
     */
    @WebMethod
    @WebResult(name = "RespuestaListaParametricas", targetNamespace = "")
    @RequestWrapper(localName = "sincronizarParametricaTipoEmision", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarParametricaTipoEmision")
    @ResponseWrapper(localName = "sincronizarParametricaTipoEmisionResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarParametricaTipoEmisionResponse")
    public RespuestaListaParametricas sincronizarParametricaTipoEmision(
        @WebParam(name = "SolicitudSincronizacion", targetNamespace = "")
        SolicitudSincronizacion solicitudSincronizacion);

    /**
     * 
     * @param solicitudSincronizacion
     * @return
     *     returns bo.gob.impuestos.sfe.synchronization.RespuestaListaParametricas
     */
    @WebMethod
    @WebResult(name = "RespuestaListaParametricas", targetNamespace = "")
    @RequestWrapper(localName = "sincronizarParametricaPaisOrigen", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarParametricaPaisOrigen")
    @ResponseWrapper(localName = "sincronizarParametricaPaisOrigenResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarParametricaPaisOrigenResponse")
    public RespuestaListaParametricas sincronizarParametricaPaisOrigen(
        @WebParam(name = "SolicitudSincronizacion", targetNamespace = "")
        SolicitudSincronizacion solicitudSincronizacion);

    /**
     * 
     * @param solicitudSincronizacion
     * @return
     *     returns bo.gob.impuestos.sfe.synchronization.RespuestaListaParametricas
     */
    @WebMethod
    @WebResult(name = "RespuestaListaParametricas", targetNamespace = "")
    @RequestWrapper(localName = "sincronizarParametricaTipoMoneda", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarParametricaTipoMoneda")
    @ResponseWrapper(localName = "sincronizarParametricaTipoMonedaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.impuestos.sfe.synchronization.SincronizarParametricaTipoMonedaResponse")
    public RespuestaListaParametricas sincronizarParametricaTipoMoneda(
        @WebParam(name = "SolicitudSincronizacion", targetNamespace = "")
        SolicitudSincronizacion solicitudSincronizacion);

}
