package bo.com.luminia.sflbilling.msinvoice.service.constants;

import bo.gob.impuestos.sfe.invoice.xml.XmlSectorType;

import java.util.HashMap;
import java.util.Map;

public class SiatInvoiceType {

    private final static Integer INVOICE_TYPE_WITH_CREDIT = 1;
    private final static Integer INVOICE_TYPE_WITHOUT_CREDIT = 2;
    private final static Integer INVOICE_TYPE_ADJUSTMENT_DOCUMENT = 3;
    private final static Integer INVOICE_TYPE_EQUIVALENT = 4;

    public static final Map<Integer, Integer> map;

    static {
        map = new HashMap<>();
        map.put(XmlSectorType.INVOICE_COMPRA_VENTA, INVOICE_TYPE_WITH_CREDIT);
        map.put(XmlSectorType.INVOICE_ALQUILER_BIENES_INMUEBLES, INVOICE_TYPE_WITH_CREDIT);
        map.put(XmlSectorType.INVOICE_COMERCIAL_EXPORTACION, INVOICE_TYPE_WITHOUT_CREDIT);
        map.put(XmlSectorType.INVOICE_EXPORTACION_LIBRE_CONSIGNACION, INVOICE_TYPE_WITHOUT_CREDIT);
        map.put(XmlSectorType.INVOICE_ZONA_FRANCA, INVOICE_TYPE_WITHOUT_CREDIT);
        map.put(XmlSectorType.INVOICE_TURISTICO_HOSPEDAJE, INVOICE_TYPE_WITHOUT_CREDIT);
        map.put(XmlSectorType.INVOICE_ALIMENTOS_SEGURIDAD, INVOICE_TYPE_WITHOUT_CREDIT);
        map.put(XmlSectorType.INVOICE_TASA_CERO_VENTA_LIBROS_TRANSPORTE_INTERNACIONAL, INVOICE_TYPE_WITHOUT_CREDIT);
        map.put(XmlSectorType.INVOICE_COMPRA_VENTA_MONEDA_ENTRANJERA, INVOICE_TYPE_WITHOUT_CREDIT);
        map.put(XmlSectorType.INVOICE_DUTTY_FREE, INVOICE_TYPE_WITHOUT_CREDIT);
        map.put(XmlSectorType.INVOICE_SECTOR_EDUCATIVO, INVOICE_TYPE_WITH_CREDIT);
        map.put(XmlSectorType.INVOICE_COMERCIALIZACION_HIDROCARBUROS, INVOICE_TYPE_WITH_CREDIT);
        map.put(XmlSectorType.INVOICE_SERVICIOS_BASICOS, INVOICE_TYPE_WITH_CREDIT);
        map.put(XmlSectorType.INVOICE_PRODUCTOS_ICE, INVOICE_TYPE_WITH_CREDIT);
        map.put(XmlSectorType.INVOICE_ENTIDADES_FINANCIERAS, INVOICE_TYPE_WITH_CREDIT);
        map.put(XmlSectorType.INVOICE_FACTURAS_HOTELES, INVOICE_TYPE_WITH_CREDIT);
        map.put(XmlSectorType.INVOICE_HOSPITAL_CLINICAS, INVOICE_TYPE_WITH_CREDIT);
        map.put(XmlSectorType.INVOICE_JUEGOS_AZAR, INVOICE_TYPE_WITH_CREDIT);
        map.put(XmlSectorType.INVOICE_HIDROCARBUROS, INVOICE_TYPE_WITH_CREDIT);
        map.put(XmlSectorType.INVOICE_EXPORTACION_MINERALES, INVOICE_TYPE_WITHOUT_CREDIT);
        map.put(XmlSectorType.INVOICE_VENTA_INTERNA_MINERALES, INVOICE_TYPE_WITH_CREDIT);
        map.put(XmlSectorType.INVOICE_TELECOMUNICACIONES, INVOICE_TYPE_WITH_CREDIT);
        map.put(XmlSectorType.INVOICE_PREVALORADA, INVOICE_TYPE_WITH_CREDIT);
        map.put(XmlSectorType.INVOICE_NOTA_CONCILIACION, INVOICE_TYPE_ADJUSTMENT_DOCUMENT);
        map.put(XmlSectorType.INVOICE_NOTA_CREDITO_DEBITO, INVOICE_TYPE_ADJUSTMENT_DOCUMENT);
        map.put(XmlSectorType.INVOICE_PRODUCTOS_NACIONALES, INVOICE_TYPE_WITH_CREDIT);
        map.put(XmlSectorType.INVOICE_PRODUCTOS_NACIONALES_ICE, INVOICE_TYPE_WITH_CREDIT);
        map.put(XmlSectorType.INVOICE_REGIMEN_7RG, INVOICE_TYPE_WITHOUT_CREDIT);
        map.put(XmlSectorType.INVOICE_BOLETO_AEREO, INVOICE_TYPE_EQUIVALENT);
        map.put(XmlSectorType.INVOICE_EXPORTACION_SERVICIOS, INVOICE_TYPE_WITHOUT_CREDIT);
        map.put(XmlSectorType.INVOICE_SEGUROS, INVOICE_TYPE_WITH_CREDIT);
    }
}
